Summary:   Now sets environment variables based upon options. Detail:   You can now rely on the options passed in the components file to   adjust the "Locale", "UserIF" and "Machine" environment variables   for a component. This allows you to build components which use   paths like "LocalRes:", "LocalUserIFRes:" in their Makefiles and   get the correct resources out.
  I also fixed the install rule in the Makefile.
Admin:
  Builds and quite thoroughly tested.

  As an aside, I do occasionally see data aborts during builds, but
  this has been seen for a couple of years and on various build
  machines. An example is:

  INSTDIR = 'ADFS::Slayer2.$.Builds.Baseline.InstallAMU: *** Internal
  error: abort on data transfer at &0380D278 ***

  (line split for clarity). I don't know if this is amu's fault or
  scrbuild not terminating strings correctly. This is always where
  things seem to fail, i.e. the Kernel outputting a string which
  aborts before reaching the terminator - at the byte which should
  be it. Maybe it is the OS_NewLine code triggers callbacks in a
  task window which occasionally causes some nasty abort?

Version 0.37. Tagged as 'srcbuild-0_37'